### ISSUE TITLE
replicated

### ISSUE THREAD

**Issue by lcddh** [Razzeeyy/godot-networked-instancing-example#1]
emit_signal("replicated", data) 
I don't see the corresponding handler for this code.

**Comment by razzeeyy** [comment]
I assume you're talking about SyncNode
the signal being emitted is this
https://github.com/Razzeeyy/godot-networked-instancing-example/blob/master/addons/sync_sys/sync_node.gd#L6

**Comment by lcddh** [comment]
I mean i did not seen connect func

**Comment by lcddh** [comment]
![image](https://user-images.githubusercontent.com/5841609/66990816-7d3a3380-f0f9-11e9-889f-bb31669536c2.png)

the spawned has

**Comment by razzeeyy** [comment]
Oh I should mention that I've changed the examples a bit, and now if you're following the video it might be outdated.
I'll ~update the docs more~ and possibly publish a newer video soon. Docs updated.

However the replicated signal and SyncNode can still be used directly if one wants, but there are now some simpler ways to synchronize transforms/rigidbodies.

~Also I'll probably push the old example as separate branch just to keep the history.~ <- done

**Comment by razzeeyy** [comment]
I made original version (that matches the video) accessible at a branch here https://github.com/Razzeeyy/godot-networked-instancing-example/tree/v1

But the replicated signal wasn't connected there too. It's usable when you want to act on some data when it's received but if you access that data regularry in _process function (what this example does) it's pretty much the same.

**Comment by lcddh** [comment]
Thank you for your reply. Another question is that GODOT is sent from the client to the server and other clients. If a client tampers with the location, what will happen and how can it be avoided?

**Comment by razzeeyy** [comment]
You can subscribe to `replicated` signal on server (or other trusted authority) and check if the recieved data looks right, and if something is wrong correction can be applied.

However there is a problem in godot 3.1 version in that it forwards messages in a manner similar to p2p. (https://github.com/godotengine/godot/issues/27932)

And right now the master nodes are more authoritative than they should be.
So it would require a little bit of adjustments to the addon to make something like explicit whitelists of which ID's we listen to.

But I need to take some time to think on that problem. But for now the addon is perfectly useable to get started fast and if cheating becomes a problem maybe more sophisticated solution would be required. I personally use it for building a coop game here because I acknowledge that Godot's networking stack need to mature itself a bit more hence I'm not putting a lot of features into the addon right now.

But if really must have fix is needed than it's possible to create your own SyncNode subclass with overrides for functions like `rpc_replicate` and `rpc_spawned` that only trust server (or other trusted authority) and nobody else.

**Comment by lcddh** [comment]
Thank you very much

**Comment by razzeeyy** [comment]
Btw @lcddh I've just rolled out version 0.4. And it features ability to write validation function to prevent cheating/hacking and other sorts of malicious clients. See here https://github.com/Razzeeyy/godot-networked-instancing-example/issues/3#issuecomment-545019593
