### ISSUE TITLE
3D version of nodes

### ISSUE THREAD

**Issue by Lucaspec72** [Razzeeyy/godot-networked-instancing-example#2]
I've been trying to modify the addon to work with 3d but i always end up with errors =| will you add a 3d version of the node(s) in the future ?

**Comment by razzeeyy** [comment]
I just did, check out `SyncTransform3D` and `SyncRigidBody3D`.
Api usage is same methods/variables as in 2D variants of those nodes, api reference can be found here
https://github.com/Razzeeyy/godot-networked-instancing-example#api-overview

If you want to just get started quick: simply use `SyncTransform3D` node instead of `SyncNode` and don't forget to check `replicated` and `interpolated` and it should just work. (It even can sync rigid bodies if you don't care about prediction stuff etc.).

**Comment by Lucaspec72** [comment]
Nice ! Thanks for the quick reply and the awesome work you make !
