### ISSUE TITLE
Invalid packet received

### ISSUE THREAD

**Issue by lcddh** [Razzeeyy/godot-networked-instancing-example#5]
![image](https://user-images.githubusercontent.com/5841609/67139940-362e7880-f288-11e9-9f2e-7f6b30cd9ccb.png)
This error occurred while connecting  the second client

**Comment by razzeeyy** [comment]
Some more context is needed, what exactly do you run an example or your own code? And did it harm in any way?

This can happen due to replication packet arriving earlier than the spawn packet so the node isn't spawned on client yet but tries to call an rpc, for now Godot just errors that (and no way to override that behavior) but it shouldn't harm the functioning in anyway.

**Comment by razzeeyy** [comment]
I'm closing this issue for now since there is no feedback,
@lcddh feel free to let me know if this error actually breaks stuff in any way.
